config/routes.rb
Rails.application.routes.draw do
 

  resources :administrators
  resources :children
  resources :guardians
  resources :roles
  
 # get 'recent'=> 'ideas#recent'
 # get 'oldest'=> 'ideas#oldest'
#  get 'filled'=> 'filled#recent'
# get 'decend'=> 'ideas#decend'
#  get 'alphabitizedasc'=> 'ideas#alphabitizedasc'
 ## #get 'helpNeeded'=> 'ideas#Needed'
  
  
  #get 'about' => '#about'
   
  get 'sessions/new' => 'sessions#new', as: :login
  
  post 'sessions/new'  => 'sessions#create'
  
  delete 'visitors/index' => 'sessions#destroy', as: :logout
  
  get 'administrators/new' => 'administrators#new', as: :signup
 

  resources :administrators do
      get :make_admin, on: :member
  end
  
  root to: 'visitors#index'
  
  # get 'login' => 'sessions#new'
  # get 'signup' => 'users#new'
  
  #post 'login' => 'sessions#create'
  # #	post 'signup' => 'session#new'
  # 	post 'signup' => 'users#create'
end 

app/models/guardian.rb
class Guardian < ActiveRecord::Base
    has_many :children
end

app/controllers/guardians_controller.rb
class GuardiansController < ApplicationController
  before_action :set_guardian, only: [:show, :edit, :update, :destroy]

  # GET /guardians
  # GET /guardians.json
  def index
    @guardians = Guardian.all
  end

  # GET /guardians/1
  # GET /guardians/1.json
  def show
  end

  # GET /guardians/new
  def new
    @guardian = Guardian.new
  end

  # GET /guardians/1/edit
  def edit
  end

  # POST /guardians
  # POST /guardians.json
  def create
    @guardian = Guardian.new(guardian_params)

    respond_to do |format|
      if @guardian.save
        format.html { redirect_to @guardian, notice: 'Guardian was successfully created.' }
        format.json { render :show, status: :created, location: @guardian }
      else
        format.html { render :new }
        format.json { render json: @guardian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guardians/1
  # PATCH/PUT /guardians/1.json
  def update
    respond_to do |format|
      if @guardian.update(guardian_params)
        format.html { redirect_to @guardian, notice: 'Guardian was successfully updated.' }
        format.json { render :show, status: :ok, location: @guardian }
      else
        format.html { render :edit }
        format.json { render json: @guardian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guardians/1
  # DELETE /guardians/1.json
  def destroy
    @guardian.destroy
    respond_to do |format|
      format.html { redirect_to guardians_url, notice: 'Guardian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guardian
      @guardian = Guardian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guardian_params
      params.require(:guardian).permit(:firstname, :lastname, :occupation, :email, :contact, :number_of_children, :relationship_to_child, :preferredLanguage)
    end
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/views/guardians/_form.html.erb
<%= simple_form_for(@guardian) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :occupation %>
    <%= f.input :email %>
    <%= f.input :contact %>
    <%= f.input :number_of_children %>
    <%= f.input :relationship_to_child %>
    <%= f.input :preferredLanguage %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/guardians/edit.html.erb
<h1>Editing Guardian</h1>

<%= render 'form' %>

<%= link_to 'Show', @guardian %> |
<%= link_to 'Back', guardians_path %>

app/views/guardians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guardians</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Occupation</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Number of children</th>
      <th>Relationship to child</th>
      <th>Preferredlanguage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guardians.each do |guardian| %>
      <tr>
        <td><%= guardian.firstname %></td>
        <td><%= guardian.lastname %></td>
        <td><%= guardian.occupation %></td>
        <td><%= guardian.email %></td>
        <td><%= guardian.contact %></td>
        <td><%= guardian.number_of_children %></td>
        <td><%= guardian.relationship_to_child %></td>
        <td><%= guardian.preferredLanguage %></td>
        <td><%= link_to 'Show', guardian %></td>
        <td><%= link_to 'Edit', edit_guardian_path(guardian) %></td>
        <td><%= link_to 'Destroy', guardian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guardian', new_guardian_path %>

app/views/guardians/new.html.erb
<h1>New Guardian</h1>

<%= render 'form' %>

<%= link_to 'Back', guardians_path %>

app/views/guardians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @guardian.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @guardian.lastname %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @guardian.occupation %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guardian.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @guardian.contact %>
</p>

<p>
  <strong>Number of children:</strong>
  <%= @guardian.number_of_children %>
</p>

<p>
  <strong>Relationship to child:</strong>
  <%= @guardian.relationship_to_child %>
</p>

<p>
  <strong>Preferredlanguage:</strong>
  <%= @guardian.preferredLanguage %>
</p>

<%= link_to 'Edit', edit_guardian_path(@guardian) %> |
<%= link_to 'Back', guardians_path %>