config/routes.rb
Rails.application.routes.draw do
 

  resources :administrators
  resources :children
  resources :guardians
  resources :roles
  
 # get 'recent'=> 'ideas#recent'
 # get 'oldest'=> 'ideas#oldest'
#  get 'filled'=> 'filled#recent'
# get 'decend'=> 'ideas#decend'
#  get 'alphabitizedasc'=> 'ideas#alphabitizedasc'
 ## #get 'helpNeeded'=> 'ideas#Needed'
  
  
  #get 'about' => '#about'
   
  get 'sessions/new' => 'sessions#new', as: :login
  
  post 'sessions/new'  => 'sessions#create'
  
  delete 'visitors/index' => 'sessions#destroy', as: :logout
  
  get 'administrators/new' => 'administrators#new', as: :signup
 

  resources :administrators do
      get :make_admin, on: :member
  end
  
  root to: 'visitors#index'
  
  # get 'login' => 'sessions#new'
  # get 'signup' => 'users#new'
  
  #post 'login' => 'sessions#create'
  # #	post 'signup' => 'session#new'
  # 	post 'signup' => 'users#create'
end 

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate, only: [:new, :create]
  before_action :super_admin, only: [:index] #, :make_admin]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:firstname, :lastname, :access_level, :contact, :school_id, :email, :password)
    end
    
    def super_admin
      if current_administrator.access_level == 2
        redirect_to root_path
      end
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= simple_form_for(@administrator) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :access_level %>
    <%= f.input :contact %>
    <%= f.input :school_id %>
    <%= f.input :email %>
    <%= f.input :password%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="blue-head">Listing Administrators</h1>



<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Access level</th>
      <th>Contact</th>
      
      <th>School</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.firstname %></td>
        <td><%= administrator.lastname %></td>
        <td><%= administrator.access_level %></td>
        <td><%= administrator.contact %></td>
        <td><%= administrator.school_id %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @administrator.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @administrator.lastname %>
</p>

<p>
  <strong>Access level:</strong>
  <%= @administrator.access_level %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @administrator.contact %>
</p>

<p>
  <strong>School:</strong>
  <%= @administrator.school_id %>
</p>
<p>
  <strong>Email:</strong>
  <%= @administrator.email%>
</p>
<p>
  <strong>Password:</strong>
  <%= @administrator.password %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>